config/routes.rb
Rails.application.routes.draw do
  get 'search_repositries/list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/', to: 'search_repositries#list', as: 'search_repositories'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_repositries_controller.rb
class SearchRepositriesController < ApplicationController

  # Rendering Repositories here
  def list
    render locals: { repos: get_repos, search_input: params[:search] }
  end

  private
  # Here we are calling Reposearch Service and passing search input
  def get_repos
    Github::RepoSearch.new.search_repository(params[:search])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_repositries_helper.rb
module SearchRepositriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubRepositorySearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search_repositries/list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Github Repos Search</title>
  <style type="text/css">

      .form {
          margin-top: 20px;
          margin-left: 10%;
      }
      </style>
</head>

<body>
<div>
  <h1>Github Repos Search</h1>
</div>
<%= form_tag(search_repositories_path, method: :get) do %>
  <div class="form" style="margin-left: 10%">
      <label for="search_bar">Please Enter Repository Here:</label>
      <%= text_field_tag :search, search_input, id: 'search_bar', placeholder: "Search Repository here", class: "form-control" %>
  </div>
<% end %>


  <% if search_input.blank? %>
    <h3>Please Enter Something in the search bar</h3>

  <% else %>

  <div class="form">
    <ul>
      <li><%= "Total Results = #{repos[:total_count]}" %></li>
      <li><%= "Incomplete Result = #{repos[:incomplete_results]}" %></li>
    </ul>
  </div>
  <div class="form">
  <% repos[:items].each do |repo| %>

        <dl>
          <dt>Id</dt> <dd><%= repo.id %></dd>
          <dt>Node Id</dt> <dd><%= repo.node_id %></dd>
          <dt>Name</dt> <dd><%= repo.name %></dd>
          <dt>Full Name</dt> <dd><%= repo.full_name %></dd>
          <dt>Description</dt> <dd><%= repo.description %></dd>
          <dt>Html URL</dt> <dd><a href= <%= repo.html_url %> ><%= repo.html_url %></a></dd>
        </dl>

      <hr style="margin-right: 10%">
  <% end %>
  </div>
<% end %>
</body>
</html>